version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://server:5000
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - WATCHPACK_POLLING=true
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev